import { type Models } from 'node-appwrite';

// This file is auto-generated by the Appwrite CLI. 
// You can regenerate it by running `appwrite types -l ts .`.

export type Products = Models.Row & {
    name: string;
    description: string | null;
    price: number;
    stock: number;
    category: string;
    image_url: string | null;
}

export type Customers = Models.Row & {
    name: string;
    email: string;
    phone: string | null;
    address: string | null;
}

export type Orders = Models.Row & {
    customer_id: string;
    total_amount: number;
    status: string;
}

export type OrderItems = Models.Row & {
    order_id: string;
    product_id: string;
    quantity: number;
    price: number;
}

export type Inventory = Models.Row & {
    product_id: string;
    quantity: number;
}

export type AdminUsers = Models.Row & {
    username: string;
    password_hash: string;
    role: string;
}

export type AnalyticsEvents = Models.Row & {
    event_type: string;
    user_id: string | null;
    product_id: string | null;
}
 
export type AnalyticsSummary = Models.Row & {
    total_page_views: number;
    unique_visitors: number;
    total_product_views: number;
    total_cart_additions: number;
    total_orders: number;
    total_revenue: number;
    top_products: string[] | null;
    top_categories: string[] | null;
}

export type Sessions = Models.Row & {
    user_id: string;
    login_time: string | null;
    logout_time: string | null;
}
